<!--- Universal Analytics Start --->
<?php $_helper = Mage::helper('baua') ?>
<?php if($_helper->isActive()): ?>
     <script type="text/javascript">
         function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google­analytics.com/analytics.js','ga');

         ga('require', 'ec', 'ec.js');
         ga('create', '<?php echo Mage::getStoreConfig("google/analytics/account") ?>','<?php echo Mage::getStoreConfig("web/unsecure/base_url") ?>');

        <?php echo $_helper->getSessionData() ?>
    </script>
    <?php $_helper->setSessionData(null) ?>
<?php endif ?>
<!--- Universal Analytics End --->