<!--- Universal Analytics Start --->
<?php $this->JS = Mage::getSingleton('baua/js'); ?>
<?php $itemsCollection = Mage::getSingleton('checkout/session')->getQuote()->getItemsCollection(); ?>
<?php $_helper = Mage::helper('baua') ?>
<?php $productArray = array(); ?>
<?php if($_helper->isActive()): ?>
    <?php foreach ($itemsCollection as $item) :?>
        <?php $result = Mage::getModel('baua/monitor')->generateProductData($item); ?>
        <?php if($result != null) : ?>
            <?php $productArray[] = $this->JS->generateGoogleJS('ec:addProduct', $result) . "\n"; ?>
        <?php endif; ?>
    <?php endforeach; ?>


    <script type="text/javascript">

        /**
	 * For some reason, magento never actually sets 'login' as a
	 * step, so we need to basically force it here.
	 */
        checkout.setMethodParent = checkout.setMethod;
        checkout.setMethod = function() {
	    this.currentStep = 'login';
	    this.setMethodParent();
        };

        /**
        * This overrides the checkout.gotoSection to perform the ga push.
        * @type {gotoSection}
        */
        checkout.gotoSectionparent = checkout.gotoSection;
        checkout.gotoSection = function(section, reloadProgressBlock) {
            ga('ec:setAction','checkout', {'step': this.steps.indexOf(this.currentStep)+1, 'label': this.currentStep });
            <?php foreach($productArray as $product) : ?>
                <?php echo $product; ?>
            <?php endforeach; ?>
            <?php echo $this->JS->generateGoogleJS('send', 'event', 'Checkout', 'Option', '')?>

            this.gotoSectionparent(section);
        };
    </script>

<?php endif ?>
<!--- Universal Analytics End --->
