<!-- Universal Analytics Start -->
<?php $helper = Mage::helper('baua') ?>
<?php if($helper->isActive()): ?>
     <script type="text/javascript">

         (window.gaDevIds=window.gaDevIds||[]).push('B7gQME');

         (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

         ga('create', '<?php echo Mage::getStoreConfig("google/analytics/account") ?>','auto');
         ga('require', 'ec');
         ga('require', 'displayfeatures');
         ga('set', '&cu', '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>');

         <?php echo $helper->generateProductImpressions() ?>
         <?php echo $helper->generatePromoImpressions() ?>

         <?php echo $helper->getAction() ?>
         ga('send', 'pageview');

         <?php echo $helper->generateProductClickEvents() ?>
         <?php echo $helper->generatePromoClickEvents() ?>
    </script>
<?php endif ?>
<!-- Universal Analytics End -->
