<!--- Universal Analytics Start --->
<?php $this->JS = Mage::getSingleton('baua/js'); ?>
<?php $order = Mage::getModel('sales/order')->loadByIncrementId(Mage::getSingleton('checkout/session')->getLastRealOrderId()); ?>
<?php $_helper = Mage::helper('baua') ?>
<?php $data = Mage::getModel('baua/monitor')->generateTransactionData($order); ?>

<?php if($_helper->isActive()): ?>

    <script type="text/javascript">
        <?php echo $this->JS->generateGoogleJS('ec:setAction', 'purchase', $data) . "\n"; ?>
    </script>

<?php endif ?>
<!--- Universal Analytics End --->